import Head from 'next/head'
import styled from 'styled-components'
import Image from 'next/image'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{width: '50%', textAlign: 'center'}}>
        <Image src="/whatsapp-home.png" height={250} width={250} />
        <h2 style={{ color: '#727372' }}>Keep your phone connected</h2>
        <p style={{ color: '#b7b9bb' }}>
          WhatsApp connects to your phone to sync messages. To reduce data usage, connect your phone to Wi-Fi.
        </p>
      </div>
    </Container>
  )
}

const Container = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #f8fafc;
  width: 100%;
  height: 100%;
`